### PR TITLE
6 new tracks

### PR DESCRIPTION
**Pull request by FQef**
Mega Man X - Storm Eagle
Mega Man X - Sting Chameleon
Mega Man X - Armored Armadillo
La Mulana - Fearless Challenger
La Mulana - Moon Light Dance
La Mulana - Mr Explorer

### CODE REVIEW

**Comment by DaruniasJoy** [comment]
will look at this tomorrow

**Comment by DaruniasJoy** [comment]
this needs work on the drumkits. otherwise they seem fine

**Comment by FQef** [comment]
Can you be more specific about the issue? One file in particular or all of them?

**Comment by DaruniasJoy** [comment]
We added a video explaining how the Drumkit of OoT works into discord #ressources. Bet that helps you a lot for future pieces. 

Will merge this now.

**Pull request merged**
