### PR TITLE
Lucky Number Show from Pokemon G/S

### PR DESCRIPTION
**Pull request by Dominator101**

### CODE REVIEW

**Comment by DaruniasJoy** [comment]
lower the volume by 10-15% and we are good to go

**Comment by Dominator101** [comment]
Okay, I think it should be quieter now? Forgive me if I did it wrong, I lowered all the 'Volume' properties in Sekaiju by about 10, but it looks like the default volume in seq64 also affected it (I assumed previously it was just a default for tracks with unset volumes). I think I used the same value in seq64, so I don't fully know if decreasing the values in Sekaiju did the trick or not, I'm still not too comfortable with most of this stuff.

**Comment by DaruniasJoy** [comment]
https://prnt.sc/-Vcmf1GI1kUV this is where you fix the overall volume of the track . ill add this manually. For future Reference in terms of volume. The volume is fine when you can clearly hear the waterfall outside of links house through the whole track.

**Comment by Dominator101** [comment]
I think I'm using the v2 of seq64, but yeah I think I know that same field. I assumed that it would use a combination of the midi's volume settings and that field, so I figured if I decreased the midi's values and used the same one there it'd still make it quieter. I'll push up a better version later today.

And yeah, I did test by the waterfall and thought it sounded fine, but maybe my audio balancing is different or I was just standing too close to it.

**Pull request closed without merging**
