### PR TITLE
Various Midi Imports (1)

### PR DESCRIPTION
**Pull request by E-Ada93**
Each commit should have a link to what the sequence should sound like in game along with some technical information about the track (including the source midi used). Decided to hold off on making a PR until I had a handful completed.

### CODE REVIEW

**Comment by darkangel93x** [comment]
Cool, sorry for the super late reply to this one! Keep on working !! :)

Temple of Droplets has 1 Single note repeating over and over (sounds like your car if you leave the door open eg) can you remove that its annoying af.
otherwise its fine  tad loud maybe but yeah thats something easy to fix :)

Nier seems fine but again volume faaaaaaaaar too loud.

Golden Sun : Flutes need to be a bit less loud as well . on Headphones they hurt in the ears.

Kingdom Hearts Dearly Beloved  totally fine :)

KH2 again too loud

sonic seems fine

**Comment by E-Ada93** [comment]
apologies for the super late response, I agree that temple of droplets sounded odd, i'm not sure i was confident enough to submit it ^^;... that was removed, the remaining tracks (besides the Sonic one) had their volumes lowered (Golden Sun's especially so) however I didn't actually test the volume adjustments in game and thus i don't have a video example (since the song data is virtually unchanged)

**Comment by darkangel93x** [comment]
will review this weekend. update your PR that it matches the current naming/folder scheme. if you adjusted everything thats an easy merge then :)

**Comment by darkangel93x** [comment]
yeah, they seem fine like this. overall rearrange this PR or open a new one with adjustments to structure,name scheme and this can be merged then.

**Comment by DaruniasJoy** [comment]
thought this was added. just did it manually now . :)

**Pull request closed without merging**
