### PR TITLE
Add python script to generate song list

### PR DESCRIPTION
**Pull request by kenokeefe91**
This script is here to help people who wants to customize their `cosmetics.json` file by themselve.

Instead of searching for the song keys directly into the file system and open each one of the `.meta` files, you just launch the script, it will create a `song_list.txt` file with all the songs sorted by licenses as it is presented into the `data/Music` directory and the key to use into the `cosmetics.json` file.

I voluntary added the `song_list.txt` file to the `.gitignore` file to prevent accidental commit and having a song list on the repository that does not match the actual one.

I also took the liberty to give some indication into the Readme so user who're reading it can have this information, I'm not a native english speaker so feel free to correct me if there is any bad grammar into it I will gladly update the pull request.

```txt
- Music
    - Kingdom Hearts Series
        - Kingdom Hearts
             key: Kingdom Hearts - Dearly Beloved
             key: Kingdom Hearts - Gummi Ship #1
             key: Kingdom Hearts - Hollow Bastion
             key: KH - Dearly Beloved
             key: Kingdom Hearts - Traverse Town
             key: Kingdom Hearts - Dive to the Heart
        - Kingdom Hearts 2
             key: Kingdom Hearts 2 Final Mix - Sora's Theme
             key: Kingdom Hearts II - Sinister Sundown
             key: Kingdom Hearts 2 Final Mix - Cavern of Remembrance
             key: Kingdom Hearts II - The 13th Struggle
    - StarTropics
         key: StarTropics - Miracola Village
         key: Dungeon - StarTropics
         key: StarTropics - Maze Like Hallways
         key: Boss - StarTropics
         key: StarTropics - Captain Bell's Memorial
    - Metroid Series
        - Metroid Prime Hunters
             key: Metroid Prime Hunters - Alinos Multiplayer
             key: Metroid Prime Hunters - Arcterras Depths
...
```

### CODE REVIEW

**Comment by DaruniasJoy** [comment]
so. i opened your repository tried it with that. tried it on mine Result :  doesnt work on my end. File stays empty. And not always shows the "song_list.txt file successfully created!" "Have fun customizing your randomizer ! :)" message

**Comment by kenokeefe91** [comment]
> so. i opened your repository tried it with that. tried it on mine Result : doesnt work on my end. File stays empty. And not always shows the "song_list.txt file successfully created!" "Have fun customizing your randomizer ! :)" message

Hmmm, that's weird, the script is supposed to look for `data/Music` directory from the location you are launching it, are you sure the songs are presents or did you already moved them to your randomizer location. 

You use it on windows I suppose ? I'm gonna test it on it and maybe add some log to see what's happening on your side

**Comment by DaruniasJoy** [comment]
Running on Windows 11
Download

**Comment by kenokeefe91** [comment]
Ok I can reproduce the bug on my w11, I'll check on that

**Comment by kenokeefe91** [comment]
@DaruniasJoy it was an issue with file encoding when creating it, I've set it up to `utf-8` explicitly and have added some catching to get why the app is crashing when it happens, you should be able to run it now and have the song_list.txt on w11

**Comment by kenokeefe91** [comment]
image

**Comment by DaruniasJoy** [comment]
works :) thx for the quick fix.

**Pull request merged**
