### PR TITLE
Assorted Additions

### PR DESCRIPTION
**Pull request by FQef**
**4 new tracks**
- Shadow of the Colossus - The Opened Way
- Pokemon Gold/Silver - Lake of Rage
- Castlevania - Vampire Killer
- Star Ocean: The Second Story - Pyroxene

**2 new fanfares**
- Gamecube Intro
- The Time is Now (John Cena's Theme)

**Minor adjustments to existing tracks**
- Edited the drumkit for Fearless Challenger to make it more accurate
- Rearranged Hollow Bastion to better match the original track

### CODE REVIEW

**Comment by DaruniasJoy** [comment]
will look at this in a few days :)

**Comment by DaruniasJoy** [comment]
as of today. You need to remove the John Cena Fanfare. See Discord what you can do with those files still.

**Comment by FQef** [comment]
removed John Cena's theme for copyright purposes

**Comment by DaruniasJoy** [comment]
add the songs to the list. if you need edit rights ask for them . i get a email.

**Pull request merged**
