### PR TITLE
SptKira PRs

### PR DESCRIPTION
**Pull request by E-Ada93**

### CODE REVIEW

**Comment by darkangel93x** [comment]
can you reduce the pitch of ALttP-Ocarina to make it less a pain in the ass for the ears?

and please edit the meta files according to this lists : [Instrumentlists](https://sites.google.com/site/deathbasketslair/zelda/ocarina-of-time/instrument-lists)

Instrumentist 0 i dunno whats inside but some of your fanfares break the music after they got played: if you need a eg. ocarina use 0x6 in the meta file and change the instrument in the .seq via seq64 to 01 :)

**Comment by E-Ada93** [comment]
(sorry on mobile while on campus) I used 0x00 for the songs since that’s the same instrument set that OoT uses for the non-warp Ocarina Songs (MM also uses the same slot) so I assumed it’d work (and I hadn’t run into any music errors in my tests, however brief they were)

https://sites.google.com/site/deathbasketslair/zelda/ocarina-of-time/instrument-sets-and-sequences

Also I’ll try to edit the LttP fanfare, I’m still learning seq64, so sorry if it’s too high pitched.

**Comment by darkangel93x** [comment]
totally fine :)

i tested them on DEV V.5.0.41 and the bgm didnt return after the fanfare, thats why im worried it maybe because you use 0 , i so far only used the ones listed by deathbasket under instrumentlists.
It could also be possible because the most instrument lists got moved into the ram (expansion pack) is the fault that the ones using "0" kill bgm.

im still far from "perfect" having a hard time with seq64 as well xD
so nothing to be sorry about.

**Comment by E-Ada93** [comment]
Fixed up the Ocarina fanfares, removed the LttP sequence for now.

**Comment by E-Ada93** [comment]
I do have a few sequences from MM that have some... creative liberty... when I tried to get them to work in OoT. Clock Town Tower (where the Mask Salesman is), Deku Palace, Woodfall Temple, Great Bay, Great Bay Temple, Last Hours (final 12 hours), Vs Majora's Mask, and the Milk Bar are the ones I've tried to make work in OoT. They are... somewhat good with the improvised instruments, but may not be a good idea for the main branch.

**Comment by darkangel93x** [comment]
That looks good, will test and probably record the songs as working when I'm home later.

**Comment by darkangel93x** [comment]
So far if you look into the Spreadsheet i finished renaming and testing your Stuff in terms of BGM
Could you eventually cut out the first dead 2sec in Stone Temple Theme?

**Comment by E-Ada93** [comment]
I'll look into Stone Tower Temple and see what I can do (all of these MM sequences are ripped from MM itself so it has to be that the dead seconds is what the "wind instrument" assigned channel is supposed to play, and instrumentlist 0x22 doesn't have a "wind" instrument, so i left that channel with an empty instrument for the moment). Also I didn't submit Mayor Office and Four Giants, those were already there ^^; and I only submitted Ikana Castle because I listened to the sample from the credits spreadsheet and thought that it's the MMR remix, not the vanilla song (which is what I submitted). My apologies about that.

**Comment by E-Ada93** [comment]
Turns out 5.1 is releasing today, I'll retest Stone Tower (and other notable songs I converted that uses 0x22) to see if they still kill the BGM after an enemy encounter once it's available

**Comment by DaruniasJoy** [comment]
Heey Brother! 

It would be great if you could rename the files to match similarly to what is already in the repository. A Fanfare folder with doubled folder names inside is quite wasteful. Just add `Fanfare - ` to the beginning of those sequences so you can tell them apart from BGM and put them in the corresponding directory.

**Comment by E-Ada93** [comment]
Reformatted my fork so that all the files follow the primary placement and naming conventions in line with the rest of everything. also included 2 more sequences, Snowfield (in Majora's Mask) and Groose Theme (under Skyward Sword). both of these have currently unknown authors and were obtained via the MMR project.

**Comment by DaruniasJoy** [comment]
Thanks brother!

I additionally added the credits to deathbasket for the two unknown artist tracks as I received word that they were almost certainly by her.

**Pull request merged**
