### PR TITLE
Added Boss Music (MM)

### PR DESCRIPTION
**Pull request by E-Ada93**
This is a perfect port of the Boss theme from MM. I initially did not add this due to the naming of "Boss Fight" confusing me, however it's actually the Majora's Wrath boss theme. As such, I renamed it to "Final Boss Phase 3" and added the normal Boss theme as "Boss Fight".

### CODE REVIEW

**Comment by darkangel93x** [comment]
Sounds pretty much like my version. Just that you left in the fade out at the end, would cut that out for a better loop.

**Comment by E-Ada93** [comment]
Oh the loop isn't working? That's odd... none of the other ripped sequences had that problem... I'll need a couple of days before i can fix it since i need to focus on school stuff...

**Comment by E-Ada93** [comment]
Which sequence were you listening to that had the loop issue? Boss Theme (the one that I inserted) isn't having any issue in this testing that I'm running.... (Final Boss Phase 3 isn't my sequence, it was already part of the repository, i just renamed it since it was misleading, it was called Boss Theme)

**Comment by darkangel93x** [comment]
My bad did read this wrong. i have uploaded the wrong majora boss battle seq . 

anyway this is mergeable asap you fix the name scheming in the meta file according to PR #13 
yes this is annoying but then we are always on the same level :)

**Comment by darkangel93x** [comment]
mergable @DaruniasJoy

**Pull request merged**
