### PR TITLE
Add Mario Kart 64 sequences

### PR DESCRIPTION
**Pull request by SlyryD**
- Choco Mountain: https://www.youtube.com/watch?v=fOl6P9w_nxo
- Frappe Snowland: https://www.youtube.com/watch?v=Wf1HDwKM81M

### CODE REVIEW

**Comment by DaruniasJoy** [comment]
They seem good. but the Frappe Snowland did you forget to create a loop or was this a simple fade out an the end ?

**Comment by SlyryD** [comment]
Yeah it loops right before the fade in the video.

**Comment by SlyryD** [comment]
> They seem good. but the Frappe Snowland did you forget to create a loop or was this a simple fade out an the end ? Either way make sure that they loop clean please.

Yeah it loops a few seconds before the fade in the video. It's actually slightly noticeable on the tambourine part, but probably good enough if it wasn't noticed :D

**Comment by SlyryD** [comment]
> > They seem good. but the Frappe Snowland did you forget to create a loop or was this a simple fade out an the end ? Either way make sure that they loop clean please.
> 
> Yeah it loops a few seconds before the fade in the video. It's actually slightly noticeable on the tambourine part, but probably good enough if it wasn't noticed :D

It happens at 1:12.

**Pull request merged**
