### PR TITLE
A few things.

### PR DESCRIPTION
**Pull request by kwrotunni**
Added: Requiem of Spirit but it's The Lick, Midna's Lament arrangement (not direct MIDI flip), original piano composition, somewhat more accurate version of the Prelude from FFVII.

Hope the line reformatting my computer did doesn't break anything.

I hereby authorize OoTR players to use "Untitled Piano Piece" and any other original compositions that I submit to this project for the purposes of Randomizer custom music and Randomizer custom music only. Any other use requires my direct permission.

### CODE REVIEW

**Comment by darkangel93x** [comment]
any problem with me uploading a sample to YT ? so people have a sample without needing to put it into oot ?

**Comment by darkangel93x** [comment]
Fix in the Requiem of Lick.meta file needed : "fanfare" not "fanfares"

**Comment by kwrotunni** [comment]
Feel free to upload a recording of Midna's Lament and the piano piece if you wish. Don't upload the Requiem; I'm hoping it'll be accepted as a SiIvagunner rip, in which case that can be linked instead.
Will fix.

**Comment by DaruniasJoy** [comment]
Hey Brother!

I'd like to add this, but it would be appreciated if you could fix the line endings, or reopen the PR allowing me to edit it to do so myself.

You should enable autocrlf so this doesn't become an issue in other repositories as well: https://help.github.com/en/articles/configuring-git-to-handle-line-endings

**Comment by kwrotunni** [comment]
I either fixed it or broke it further.

**Comment by kwrotunni** [comment]
If it didn't work, feel free to fix it.

**Comment by kwrotunni** [comment]
Actually, I'm going to try reverting and recommitting.

**Comment by kwrotunni** [comment]
...That may or may not have helped.

**Comment by DaruniasJoy** [comment]
We'll go with this Brother and assume git will know what it is doing from now on. Thank you!

**Comment by darkangel93x** [comment]
Well since silvagunner ripped it and clearly states he does not own any rights I'll upload the requiem thing probably too. (can mention him though eventually)

**Pull request merged**
